spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pickfolio_auth
    username: pickfolio_user
    password: pickfolio_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: "http://localhost:8080/oauth2/jwks"

jwt:
  accessTokenExpiryTime: 600000 # in milliseconds (10 minutes)
  refreshTokenExpiryTime: 604800000  # in milliseconds (7days)
  secret: ${JWT_SECRET:your-default-secret} # Use an environment variable or default value

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off